name: Build and Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Prepare Release"]
    types:
      - completed
  push:
    branches:
      - release/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if the push is the initial branch creation
        id: check-initial-push
        run: |
          if [ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]; then
            echo "Initial branch creation detected, skipping build_and_deploy."
            exit 0
          fi
        shell: bash

      - name: Download prepare_release artifact
        id: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: prepare_release_done
          path: ./prepare_release_artifact
        continue-on-error: true

      - name: Check if prepare_release is done
        id: check-prepare-release
        run: |
          if [ ! -f ./prepare_release_artifact/prepare_release_done.txt ]; then
            echo "prepare_release not done, skipping build_and_deploy."
            exit 0
          else
            echo "prepare_release_done=true" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Build and deploy
        if: env.prepare_release_done == 'true'
        run: |
          echo "Building and deploying..."
          # Add your build and deploy logic here
